### ISSUE TITLE
CPU load on VM

### ISSUE THREAD

**Issue by fedemonte89** [ajurge/CPU_load#1]
Thank you for your script! It's very useful!
Now I want to use it on a Virtual Machine installed in vmWare vCenter environment, but I noticed that it uses always 100% of cpu (with 1 or 2 cores) despite I set as input less than 100.
Do you know what possible issue is it?

Thank you in advance.

**Comment by ajurge** [comment]
It seems that the script starts the stress processes which load load each
of the cores at 100%, however cpulimit does not limit it to the given
value. You need to make sure that cpulimit is provided with the correct
stress process pids, try uncommenting line 166 and 167 and verify that the
stress process pids are the same as the ones generating the load in the
process list when the CPU load script is still running.

**Comment by fedemonte89** [comment]
I solve the problem!
I don't have total control of the vm, but probably it has installed an old version of cpu limit.
I removed -b option and added & to the end of line.
This is my 177 line:
sudo cpulimit -p $PID -l $CPULIMIT >/dev/null 2>&1 &

Now everything is ok :) !
